### ISSUE TITLE
QSM_container.simg download - file not working

### ISSUE THREAD

**Issue by Romarieth** [vzachari/IronSmithQSM#10]
Dear Prof Zachariou,

There seems to be an issue with the QSM_container.simg file I downloaded via the link you provided: 
https://drive.google.com/file/d/1NFV2z0yIEPKGblQVrcMe8bza8ZS21AO7/view?usp=sharing

The file is found in the Functions folder, but after re-downloading, I still get the following error-message:
ERROR  : Unknown image format/type: /home/668866/IronSmith/IronSmithQSM-1.2/Functions/QSM_Container.simg
ERROR: QSM_Container.simg test FAILED!

I already tried with Ironsmith v1.2 and v1.3

Currently using:
- Ubuntu 16.04.7

Thank you for your answer in advance!
Best regards

**Comment by vzachari** [comment]
Greetings,

I'll attempt to replicate your error on my end and get back to you with a solution in the next few days,

Thank you,

**Comment by vzachari** [comment]
Hello,

I re-downloaded the QSM container locally and things appear to work on my end. Do you have Singularity installed on Ubuntu 16.04.7? For example, if you type singularity --version do you get an output like "singularity-ce version 4.0.0" ?

Thank you

**Comment by Romarieth** [comment]
Greetings,

Thank you for your help. Actually I didn't have the right singularity version installed and will try now. Sorry to have bothered you with that. 

Thank you

**Comment by vzachari** [comment]
Just checking in to see if you need anything else from me. OK to close this issue?

**Comment by Romarieth** [comment]
Yes its okay to close, it works now, thank you!

**Comment by jarrelscy** [comment]
@Romarieth I am facing the same issue that you have but I have Singularity-ce 4.2.1 installed. How did you get this running?
