### ISSUE TITLE
Will there be a docker version?

### ISSUE THREAD

**Issue by sungoku** [vzachari/IronSmithQSM#2]
Hi,
After reading about your nice paper in NI, I finally got here, with hope. As I already installed docker, you know, like fmriprep etc. I am looking for a docker version of this package if possible. Can you please provide a docker container version or a simple instruction on how to build IronSmithQSM as a docker image or  just provide a DockerFile?
Thank you!

**Comment by vzachari** [comment]
Apologies for the late response. I'll add this to my to do list. I think I will opt for one version of Ironsmith that can work both with docker and singularity. I'll aim for this functionality to be added late this summer. Thank you for the input.

**Comment by sungoku** [comment]
Happy to know this, thank you.
