### ISSUE TITLE
 MEDI Toolbox and supports versions

### ISSUE THREAD

**Issue by Double94** [vzachari/IronSmithQSM#4]
Hello,
I tried to run Ironsmith on Ubuntu 22.04. The version of MATLAB is “2021b” and the version number is “9.11”, but it prompts that the version is too old (read as “9.1”), how can I solve them?
Looking forward to your reply. Thank you very much!

**Comment by vzachari** [comment]
Greetings,

MEDI Toolbox, which Ironsmith uses to create QSM maps, supports MATLAB versions R2017b to R2019b. Unfortunately 2021b won't work at the moment,

I would recommend MATLAB R2019b with the Image processing Toolbox installed,

Thank you,
