### ISSUE TITLE
Error where QSM Dicoms are not found

### ISSUE THREAD

**Issue by christine-tnp** [vzachari/IronSmithQSM#6]
Hello,

I am having an issue where Ironsmith is only able to find the QSM dicom directory for one of my participants. I have been able to successfully run 1 participant. Now I am trying to run ironsmith for 10 participants. The data for each of the participants is organized the same, and Ironsmith is able to successfully find all participant's MPR files. However, ironsmith is unable to find 9 out of the ten participant's mag/phase files. 

The first 9 participants in the csv input file get an error something like this when it comes to finding the QSM dicoms:
ERROR: QSM DICOM directory: /raw_data/iron_data/ironsmith_batc NOT FOUND in specified path! Skipping 9998...

But the last participant's files are successfully found:
QSM DICOM directory: /raw_data/iron_data/ironsmith_batchtest2/9999/9999_magphasecombo FOUND! Checking folder contents

All of the participants are organized the same way. Within the directory "ironsmith_batchtest2", each participant has their own directory, and then within each participant directory are 2 separate directories for the MPR and QSM Dicom files. I'm not sure why only the last participant is processed correctly. 

Any suggestions/advice would be helpful. Thanks!

**Comment by vzachari** [comment]
Hello,

Happy to help. Every time Ironsmith runs, it creates a log file under IronSmithQSM/LogFiles, where IronSmithQSM is the installation folder of Ironsmith on your computer. The log file names are "Output.Ironsmith_date_time.txt. Can I have one of these log files with the error you describe? You maybe able to to attach one of these .txt files here,

Thank you,

**Comment by christine-tnp** [comment]
Hi,

Since the files are pretty big, I will email them to you. I was able to successfully run two instances of Ironsmith at the same time on different terminals using the same input file. I'll email you the log file for the unsuccessful run and one of the successful ones. 

Thanks!

**Comment by vzachari** [comment]
Issue was related with Ironsmith correctly dealing with Windows line endings under Ubuntu > 18.04. Issue resolved in latest beta version of Ironsmith
